# Используем официальный образ Node.js
FROM node:16

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json (или yarn.lock) из папки frontend
COPY ./frontend/package*.json ./

# Устанавливаем зависимости
RUN yarn install

# Копируем все файлы фронтенда в контейнер
COPY ./frontend /app

# Открываем порт для фронтенда
EXPOSE 3000

# Запускаем Vite для разработки
CMD ["yarn", "dev"]
